### ISSUE TITLE
希望对网站增加magnet嗅探

### ISSUE THREAD

**Issue by lyjhyjyes** [reducm/Ed2kChromePlugin#13]
《谎言真探》电视剧全集迅雷下载_MP4电影
https://www.mp4vod.com/detail/30655.html
谎言真探仅能嗅探到一个magnet链接，对磁力链接支持不太完善。
而在《叛逆者》电视剧全集迅雷下载_MP4电影
https://www.mp4vod.com/detail/30634.html
能嗅探全部ed2k链接，magnet链接还是只有一个。
这个宝藏下载网站一直使用，希望增加支持，感谢

**Comment by reducm** [comment]
好的，感谢你的使用，最近的一个大版本将会加入支持

> 《谎言真探》电视剧全集迅雷下载_MP4电影
> https://www.mp4vod.com/detail/30655.html
> 谎言真探仅能嗅探到一个magnet链接，对磁力链接支持不太完善。
> 而在《叛逆者》电视剧全集迅雷下载_MP4电影
> https://www.mp4vod.com/detail/30634.html
> 能嗅探全部ed2k链接，magnet链接还是只有一个。
> 这个宝藏下载网站一直使用，希望增加支持，感谢

**Comment by lyjhyjyes** [comment]
> 好的，感谢你的使用，最近的一个大版本将会加入支持
> 
> > 《谎言真探》电视剧全集迅雷下载_MP4电影
> > https://www.mp4vod.com/detail/30655.html
> > 谎言真探仅能嗅探到一个magnet链接，对磁力链接支持不太完善。
> > 而在《叛逆者》电视剧全集迅雷下载_MP4电影
> > https://www.mp4vod.com/detail/30634.html
> > 能嗅探全部ed2k链接，magnet链接还是只有一个。
> > 这个宝藏下载网站一直使用，希望增加支持，感谢

感谢，下载电影方便太多了
