### ISSUE TITLE
能否增加thunder://之类的支持？

### ISSUE THREAD

**Issue by eGust** [reducm/Ed2kChromePlugin#3]
或者我fork一个？

**Comment by anonymouswhac** [comment]
同样的需求，求支持thunder开头，远程下载非常有用。

**Comment by eGust** [comment]
欢迎使用我开发的版本：

https://chrome.google.com/webstore/detail/batch-links-helper/lfbpkiegcfglhhamfddbooooggiemkhn

**Comment by anonymouswhac** [comment]
谢谢，已经使用上了~
