### ISSUE TITLE
请作者回复一下，此插件这个项目是不是放弃了？

### ISSUE THREAD

**Issue by tea1111980** [reducm/Ed2kChromePlugin#7]
如题：请作者回复一下，此插件这个项目是不是放弃了？

**Comment by reducm** [comment]
@tea1111980 到目前为止使用一切正常呀，的确太久没更新，后续再更新下

**Comment by suclogger** [comment]
http://www.msj1.com/archives/402.html#download 这个页面无法复制 @reducm

**Comment by reducm** [comment]
> http://www.msj1.com/archives/402.html#download 这个页面无法复制 @reducm

![image](https://user-images.githubusercontent.com/1086830/68635283-01ce7500-0533-11ea-8888-e56fd7f042d9.png)

我最近也迷绝命毒师想和女朋友重温，也是这边复制的，ed2k是支持的，magnet估计有bug
